.TH "atdtool" 1 "" ""


.SH NAME

.P
atdtool \- After the Deadline command\-line tool

.SH SYNOPSIS

.P
\fBatdtool\fR \-h

.P
\fBatdtool\fR [\-e/error] [\-k/key=<key>] <files...>

.P
\fBatdtool\fR [\-e/error] [\-k/key=<key>] \-l/\-\-language <fr/de/pt/es> <files...>

.P
\fBatdtool\fR [\-e/error] [\-k/key=<key>] \-s/\-\-server <server> <files...>

.SH DESCRIPTION

.P
\fBatdtool\fR is a command\-line tools that contacts an After the Deadline language
service and displays the errors reported by the service in a format very similar
to gcc's.

.P
\fBAfter the Deadline\fR is a language checker that is able to:

.RS
.IP \(bu 3
spell check contextually
.IP \(bu 3
check style
.IP \(bu 3
check grammar
.RE

.P
The official server is free for personal use. They provide a free server for
commercial use. atdtool can be used with the default server or with a
custom one.

.SH OPTIONS

.P
\fB\-h\fR Help.

.P
\fB\-e, \-\-error\fR Exit with error when any error is found.

.P
\fB\-k, \-\-key=<key>\fR Selects the key to use. AtD servers cache results based on
this parameter.

.P
\fB\-l, \-\-language=[fr/de/pt/es]\fR Selects the language. This affects the server used.

.P
\fB\-s, \-\-server=<server>\fR Use a custom server.

.SH Vim integration

.P
atdtool can be used as a \fIquickfix\fR program in Vim with the following command:

.nf
:set makeprg=atdtool\e %
.fi


.P
You can then use :make to check the current buffer and navigate the errors
with the quickfix window, the same way gcc's errors can be navigated.

.P
More information on quickfix can be found with :help quickfix in Vim or at
http://vimdoc.sourceforge.net/htmldoc/quickfix.html

.SH AUTHORS

.P
Written by Leandro Penz (http://lpenz.github.com), based on the python bindings
by Miguel Ventura at http://bitbucket.org/miguelventura/after_the_deadline/wiki/Home.

.SH SEE ALSO

.RS
.IP \(bu 3
http://www.afterthedeadline.com/
.IP \(bu 3
http://bitbucket.org/miguelventura/after_the_deadline/wiki/Home.
.RE

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man -i manual.t2t -o atdtool.1
